name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: gh cli auth
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - uses: actions/setup-dotnet@v1

      - name: Install GitVersion
        run: git fetch --unshallow && dotnet tool install --global GitVersion.Tool

      - name: Get semver
        id: semver
        run: echo "SEMVER=$(dotnet gitversion | jq -r '.FullSemVer')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ secrets.GHCR_USER }}/samuelbagattin
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern=${{ env.SEMVER }}
            type=sha
      - name: Build and push
        uses: docker/bake-action@master
        with:
          tags: |
            type=semver,pattern={{version}},value=${{ env.SEMVER }}
          push: true
