name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: gh cli auth
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - uses: actions/setup-dotnet@v1

      - name: Install GitVersion
        run: git fetch --unshallow && dotnet tool install --global GitVersion.Tool

      - name: Get semver
        id: semver
        run: echo "SEMVER=$(dotnet gitversion | jq -r '.FullSemVer')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/bake-action@master
        with:
          set:
            morpio.tags=['ghcr.io/samuelbagattin/morpio:${{ env.SEMVER }}']
          push: true
